#გამოიყენეთ ყველა შედარების ოპერატორი და გააკეთეთ 15 მაგალითი თითო შედარების ოპერატორზე, (<.>.!=.==)\

# 1. < (მცირეა)
print(5 < 10)   
print(3 < 7)    
print(1 < 0)    
print(-5 < 0)   
print(0 < 100)  

# 2. > (მეტია)
print(8 > 3)    
print(15 > 12) 
print(-2 > -3)  
print(0 > -5)   
print(100 > 99) 

# 3. <= (მცირეა ან ტოლი)
print(4 <= 5)  
print(7 <= 7)   
print(0 <= 1)  
print(-1 <= 0)  
print(100 <= 50) 

# 4. >= (მეტია ან ტოლი)
print(5 >= 3)   
print(6 >= 6)   
print(-2 >= -3) 
print(0 >= -1)  
print(-100 >= -99) 

# 5. == (ტოლია)
print(5 == 5)        
print("hello" == "hello")  
print(10 == "10")   
print(False == False)  
print(None == None)     

# 6. != (არ არის ტოლი)
print(5 != 3)       
print("apple" != "orange")  
print(10 != 10)     
print(True != False)   
print(None != "none")   
